version: "3"
networks:
  jenkins-grid-net:
    driver: bridge
  healenium:
    driver: bridge

services:
  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium_user
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium


  selenium-hub:
    image: selenium/hub:4.25.0
    container_name: selenium-hub
    environment:
      - SE_OPENTELEMETRY_DISABLED=true
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - jenkins-grid-net

  chrome:
    image: selenium/node-chrome:4.25.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_OPENTELEMETRY_DISABLED=true
    networks:
      - jenkins-grid-net

  firefox:
    image: selenium/node-firefox:4.25.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - jenkins-grid-net

  edge:
    image: selenium/node-edge:4.25.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - jenkins-grid-net


  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-grid-net

volumes:
  jenkins_home: